### ISSUE TITLE
Wrong horus frequency

### ISSUE THREAD

**Issue by Mika-1818** [Nevvman18/rs41-nfw#10]
The standard freqency is 434.74 though it should be 434.714. Please correct.

**Comment by videobuff** [comment]
Good eveningI do not agree. There are at least two frequenties which are frequently used. When there are two or even three flights in the air it is easier to separate the frequencies. So leave them at a non harmful interfering frequency Thirdly I rather have the power set at low level so that experimenting does not lead to receiver congestion. To set everything to proper flight values should be no problem for  everyone. As Franek stated the values are in the first 100 lines. Met vriendelijke groetenErik SchottOp 18 okt 2024 om 16:12 heeft Franek ***@***.***> het volgende geschreven:﻿
There are various standard frequencies for Horus mode, including 434.714MHz, but also there is a popular 437.6MHz.
The reason for choosing 434.74 was only for development purposes and testing, including binary firmware releases (manual states that the defaults of binary releases shouldn't be used for HAB flights). The 434.74 frequency is usually in the range of ISM band, which doesn't require a license and would be legal for everyone. It also prevents spamming the Amateur-SondeHub servers by accidentally sending data on the monitored channels (434.714 and 436.7).
However if more people prefer the default 434.714 or 434.76, I can change that.
