### ISSUE TITLE
batteryCutOffVoltage / what after that ?

### ISSUE THREAD

**Issue by zanco** [Nevvman18/rs41-nfw#5]
Hi,
I flew a new model RS41 today , forgot to set the txpower to stage 5 so the battery appeared to drop quite quickly.

Last report after burst was at 1.92 Volt.

The batteryCutOffVoltage is set for 1.9 volt, but I would like to know what happens if the battery voltage raises again. Is there a chance the transmitter starts again ?

The 1.92 volt happened after decent at 17 km so now I have no clue where the payload ended.

**Comment by Nevvman18** [comment]
No, the sonde switches fully OFF when the batteryCutOffVoltage is reached.
The threshold is configured as a safety feature, which prevents the batteries from draining below safe voltage, because for example alkaline batteries could leak if hardly discharged at higher current rates, or when the NiNH rechargable batteries are used, to elongate their overall lifetime.
The batteryCutOffVoltage can be set lower than the default 1.9V, or even disabled by setting to 0V, which means that the sonde will work until the components are below their voltage working threshold, that method uses nearly all the battery capacity.
The firmware currently doesn't have any option to turn ON the sonde after discharging. There isn't much power left after  discharging so it wouldn't work for much longer. Also, the MCU would need to stay ON all the time to monitor the voltage, which would also force us to turn OFF all the other components, which can't be done due to the power supply stage, that is powering the whole board.

Also, to lengthen the battery life of the sonde, you can tweak some settings.
Besides the radio PA adjustment, you can change how frequently the data is sent via radio, but it could have an impact on the readings resolution.
The most important part: the firmware also has an algorithm for heating the on-board oscillator using the reference heating resistors. This is a VERY power hungry option (doubles the current consumption of the default state) and is only recommended if you use the RTTY modulation (the on board oscillator changes its parameters according to temperature, which leads to synchronization issues when the RTTY mode is used, leading to a non-decodable transmission) and using good, factory new, alkaline batteries. If you don't plan on using the RTTY, consider switching the heating off by setting the `refHeatingMode` to 0 (OFF). The default setting is 1 (AUTO), but it is only for testing purposes on ground. 
The recommended transmission mode is Horus, which is greatly tested and works in all scenarios, + is very sensitive, allowing usage of lower radio power. It also works in all temperatures, allowing for completely disabling the heating algorithm.

All functions described above are described in detail in the [operation manual here](https://github.com/Nevvman18/rs41-nfw/blob/main/fw/OPERATION_MANUAL.md), and I recommend reading it from beginning to the end and tweaking some settings in the firmware, to know exactly how the device works.

Thanks for your question, I hope that this helps.

Best,
Franek
